### ISSUE TITLE
Unable to handle sequential tokens

### ISSUE THREAD

**Issue by JGLAHE** [DungGramer/vs-aligner#1]
Hey, thanks for taking time to develop this great extension!

I don't work with frontend stuff (mostly scripting) and 50% of time this extension does what I need...

However, consider the following perl code block:
```
 die   qq{\n \$abs_filepath undefined or empty.\n}                           . EXIT_MSG_     unless  undef_empty($abs_filepath);
die                   qq{\n Absolute path '$abs_filepath' does not exist.\n}         .       EXIT_MSG_  unless     -e          $abs_filepath;
        die        qq{\n Absolute file path '$abs_filepath' is not a regular file.\n} . EXIT_MSG_            unless -f          $abs_filepath;
  die             qq{\n Absolute file path '$abs_filepath' is not readable.\n}  .     EXIT_MSG_      unless -r          $abs_filepath;
```
Maybe I'm mis-interpreting how the setting work, but it currently takes me several steps modifying settings.json and re-running (and manual editing)  to get:
```
        die qq{\n \$abs_filepath undefined or empty.\n}                        . EXIT_MSG_ unless undef_empty($abs_filepath);
        die qq{\n Absolute path '$abs_filepath' does not exist.\n}             . EXIT_MSG_ unless -e          $abs_filepath;
        die qq{\n Absolute file path '$abs_filepath' is not a regular file.\n} . EXIT_MSG_ unless -f          $abs_filepath;
        die qq{\n Absolute file path '$abs_filepath' is not readable.\n}       . EXIT_MSG_ unless -r          $abs_filepath;
```

My at any given step, my setting.json would be e.g.
```
    "autoalign.moveableItems": [
        "=",
        //":",
        "+=",
        "-="
    ],
    "autoalign.nonMoveableItems": [
        "==",
        "!=",
        "*",
        "<=",
        ">=",
        "=<",
        "for(",
        "for (",
        "if(",
        "if (",
        "-(",
        "- (",
        "(\"",
        "('",
        "(`",
        "=~",
        "&:",
        ">:",
        "*:",
        "::",
        ":active",
        ":checked",
        ":disabled",
        ":empty",
        ":enabled",
        ":first-",
        ":focus",
        ":hover",
        ":in-range",
        ":invalid",
        ":lang",
        ":last-",
        ":link",
        ":not",
        ":nth-",
        ":only-",
        ":optional",
        ":out-of-range",
        ":read-",
        ":required",
        ":root",
        ":target",
        ":valid",
        ":visited",
        "`",
        "http:",
        "https:"
    ],
    "autoalign.nonMoveableItemsAdditional": [
        //"/",
        //": ",
        ".\n}",

    ],
    "autoalign.minSeparationLeft": 0,
    "autoalign.moveableItemsAdditional": [
        //" die",
        " unless",
        //"#",
        //" .",
        //"=>"
    ],
    "autoalign.skipLinesEndingWithItems": [

        //"{",
        //"["
    ],
    "autoalign.skipLinesEndingWithItemsAdditional": [

    ],
    "autoalign.columnWidth": 1,
    "autoalign.separationRight": 0,
}
```
 where `.\n}` in
```
    "autoalign.nonMoveableItemsAdditional": [
        //"/",
        //": ",
        ".\n}",
```
  isn't recognized, meaning  I have to delete the "." in the printing statement and use `" .",` to match the concatenation operator, thus
```
    "autoalign.moveableItemsAdditional": [
        //" die",
        " unless",
        //"#",
        " .",
        //"=>"
    ],
```
However, it seems only one token can be active at a time, e.g. if `autoalign.moveableItemsAdditional` was set as above, only the `" ."` would be aligned, and the `" unless"` would be ignored, meaning several iterations are required to get all tokens aligned).

Is there an obvious solution to this that I'm missing?

Cheers, thanks again!

**Comment by DungGramer** [comment]
Hi [JGLAHE](https://github.com/JGLAHE),
I wanted to let you know that I've released a new version of the repository that addresses the bug you reported.

With this solution, I added config delimiter, you can define what character want to align.
Example:
![image](https://github.com/DungGramer/vs-aligner/assets/42514846/f892c6b3-b8c3-42e3-b612-a39416bee546)

Please check out the latest version and let me know if everything works as expected.

If you find the repository helpful, I'd really appreciate it if you could star it or leave a comment. This helps me a lot and encourages me to keep improving the project.

Thank you for your support and feedback!
